# Generated by Django 6.0.4 on 2026-04-07 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('quantita', models.PositiveIntegerField(default=0)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inserimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prodotti', to='myapp.categoria')),
            ],
            options={
                'verbose_name_plural': 'Prodotti',
                'ordering': ['-data_inserimento'],
            },
        ),
    ]
