# Generated by Django 6.0.4 on 2026-05-16 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_prodotto_immagine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'ordering': ['-data_inserimento'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='descrizione_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descrizione_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descrizione_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descrizione_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome_it',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='nome_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='nome_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='nome_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='nome_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descrizione',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prodotti', to='myapp.categoria', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='data_aggiornamento',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='data_inserimento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='descrizione',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='quantita',
            field=models.PositiveIntegerField(default=0, verbose_name='quantity'),
        ),
    ]
