# Generated by Django 6.0.4 on 2026-05-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_migrate_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descrizione_ar',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nome_ar',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='descrizione_ar',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='nome_ar',
        ),
    ]
