# Generated by Django 6.0.4 on 2026-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_categoria_descrizione_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descrizione_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='nome_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='nome_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
